#!/bin/bash
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
set -ex

if ! charms.reactive is_state 'spark.started'; then
    action-fail 'Spark not yet ready'
    exit
fi

NUM_PARTITIONS=`action-get partitions`

# create dir to store results
RUN=`date +%s`
RESULT_DIR=/opt/sparkpi-results
RESULT_LOG=${RESULT_DIR}/${RUN}.log
mkdir -p ${RESULT_DIR}
chown -R ubuntu:ubuntu ${RESULT_DIR}

benchmark-start
START=`date +%s`
# NB: Vars (e.g., ${NUM_PARTITIONS}) are
# parameterized from this outer scope
su ubuntu << EOF
. /etc/environment
echo 'calculating pi'
spark-submit --class org.apache.spark.examples.SparkPi \
  /usr/lib/spark/lib/spark-examples-*.jar ${NUM_PARTITIONS} &> ${RESULT_LOG}
EOF
STOP=`date +%s`
benchmark-finish

DURATION=`expr $STOP - $START`
benchmark-composite "${DURATION}" 'secs' 'asc'
benchmark-raw ${RESULT_LOG}
